name: devel-release
on:
  push:
    branches:
      - master
jobs:
  push_rust_iml:
    name: Push to Copr devel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Push RPM
        uses: ./.github/actions/copr-rust
        env:
          PROD: false
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-devel
          PACKAGE: rust-iml
          SPEC: rust-iml.spec
          WORKSPACE: ${{ github.workspace }}
          RUSTUP_TOOLCHAIN: stable-x86_64-unknown-linux-gnu
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
  push_iml_wasm:
    name: Push to Copr devel (WASM)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Push RPM
        uses: ./.github/actions/copr-wasm
        env:
          PROD: false
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-devel
          PACKAGE: iml-wasm-components
          SPEC: iml-wasm-components/iml-wasm-components.spec
          WORKSPACE: ${{ github.workspace }}/iml-wasm-components
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
  push_iml_gui:
    name: Push to Copr devel (GUI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Push RPM
        uses: ./.github/actions/copr-wasm
        env:
          PROD: false
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-devel
          PACKAGE: rust-iml-gui
          SPEC: iml-gui/rust-iml-gui.spec
          WORKSPACE: ${{ github.workspace }}
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
  push_iml_docker:
    name: Push to Copr devel (iml-docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build the iml images
        working-directory: ./docker
        run: |
          make save
          docker image ls

      - name: Push RPM
        uses: ./.github/actions/copr
        env:
          PROD: false
          OWNER: managerforlustre
          PROJECT: manager-for-lustre-devel
          PACKAGE: iml-docker
          SRPM_TASK: iml-docker-srpm
          SPEC: iml-docker.spec
          WORKSPACE: ${{ github.workspace }}
          KEY: ${{ secrets.key }}
          IV: ${{ secrets.iv }}
